name: example
description: An example for yx_scope_linter rules
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  yx_scope: ^0.1.1

dev_dependencies:
  lints: ^2.0.0
  custom_lint:
  yx_scope_linter:
    path: ..
